### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by undefinedCody** [godfuzz3r/burp-ununicode#1]
Hi.
I hope you are doing great.
Thank you for this great extension, it's very helpful.

Would it be possible for you to add the websocket support? It's the only missing feature of your extension.

Cheers

**Comment by godfuzz3r** [comment]
Hi, I’m not very familiar with the burp suite api, I'll try to check if it’s possible to add the same overlay for websockets.

**Comment by godfuzz3r** [comment]
Hello, rewrote with montoya api, now there is support for websockets

**Comment by undefinedCody** [comment]
@godfuzz3r Hi. I apologize for missing your comment.
Thank you so much!!! This is going to make stuff much easier.

Best.
